Repository ExpressGateway/express-gateway, pull requests merged in 2018-04, with the labels that each got.

#682 added commercial support information
  README.md
Labels: in progress

#681 Deprecate the proxyOptions object
  lib/policies/proxy/proxy.js
  package-lock.json
  package.json
  test/policies/proxy/proxy.test.js
Labels: in progress

#683 Explicitly send expires_in field
  lib/policies/oauth2/oauth2-server.js
  test/oauth/authorizationcode.test.js
  test/oauth/bootstrap.js
  test/oauth/client.test.js
  test/oauth/implicit.test.js
  test/oauth/password.test.js
  test/oauth/testUtils.js
Labels: in progress

#690 Admin API: improve query capabilities for Users and Applications
  admin/apps.js
  admin/users.js
  lib/services/consumers/application.dao.js
  lib/services/consumers/application.service.js
  lib/services/consumers/user.dao.js
  lib/services/consumers/user.service.js
  test/rest-api/applications.js
  test/rest-api/users.js
Labels: in progress

#693 Use gateway output instead of timers to signal the gateway is ready
  bin/generators/tokens/revoke.js
  test/common/gateway.helper.js
Labels: in progress

#704 Add endpoint to return all the credentials
  admin/credentials.js
  bin/generators/credentials/list.js
  lib/rest/routes/credentials.js
  lib/services/credentials/credential.dao.js
  test/cli/credentials/list.test.js
Labels: in progress

#697 Replace selenium and webdriver with puppetter
  .circleci/config.yml
  package-lock.json
  package.json
  test/common/gateway.helper.js
  test/e2e/basic-auth.e2e.test.js
  test/e2e/key-auth.e2e.test.js
  test/e2e/oauth2-authorization-code.js
  test/e2e/proxy-through-proxy.test.js
  test/fixtures/authorization-code/gateway.config.yml
  test/fixtures/authorization-code/system.config.yml
Labels: test

#706 Spell thrown error correctly on apps routes
  lib/rest/routes/apps.js
  test/rest-api/applications.js
Labels: bug, test

#707 Make sure cli start URL does not end with a slash
  bin/eg-generator.js
Labels: bug, test

#700 Expose server
  lib/index.js
Labels: test

#695 DRY the startGatewayInstance function in tests
  test/common/gateway.helper.js
  test/e2e/basic-auth.e2e.test.js
  test/e2e/key-auth.e2e.test.js
  test/e2e/oauth2-authorization-code.js
  test/e2e/proxy-through-proxy.test.js
  test/e2e/round-robin.test.js
Labels: in progress
